# 生产环境配置文件
# @author <a href="https://github.com/lixw">程序员鱼皮</a>
# @from <a href="https://xw.icu">编程导航知识星球</a>
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      routes:
        - id: xwoj-backend-user-service
          uri: lb://xwoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: xwoj-backend-question-service
          uri: lb://xwoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: xwoj-backend-judge-service
          uri: lb://xwoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: xwoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2